---
title: "listcols"
output: html_document
date: "2023-11-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

set.seed(12345)
```

### Lists

```{r}
vec_numeric = c(1:4) 
vec_character = c("my", "name", "is", "courtney")

tibble(
  num = vec_numeric,
  char = vec_character
)
```

This only works because they're the same length. But we can circumvent this by using lists instead of a tibble

```{r}
l = 
  list(
    vec_numeric = 1:5,
    vec_char = LETTERS,
    matrix = matrix(1:10, nrow = 5, ncol = 2),
    summary = summary(rnorm(100))
  )
l
```

Accessing lists

```{r}
l$vec_char
l[[2]]
l[["summary"]]
```

## Loops

```{r}
list_norm_samples = 
  list(
    a = rnorm(20, 1, 5),
    b = rnorm(20, 0, 7),
    c = rnorm(20, 20, 1),
    d = rnorm(20, -45, 13)
  )
```

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    
    stop("Argument should be numbers")
    
  }  else if (length(x) < 2) {
    
    stop("You need at least 2 numbers to get z scores")
    
  }
  
  mean_x = mean(x)
  
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
}
```

Could call the function for a:d, but that's annoying. 

```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = mean_and_sd(list_norm_samples[[i]])
}

output
```

## Now let's try using a map function

```{r}
output2 = map(list_norm_samples, mean_and_sd)
output2
```

## listcols in DFs

```{r}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"),
    sample = list_norm_samples
  )

listcol_df |> 
  pull(sample)

mean_and_sd(listcol_df$sample[[1]])
mean_and_sd(listcol_df$sample[[2]])
mean_and_sd(listcol_df$sample[[3]])
mean_and_sd(listcol_df$sample[[4]])

map(listcol_df$sample, mean_and_sd)

listcol_df |> 
  mutate(mean_sd = map(sample, mean_and_sd)) |> 
  mutate(median = map(sample, median)) |> 
  select(name, mean_sd) |> 
  unnest(mean_sd)
```


